mappings:
  ForumDatabaseSearch: SilverStripe\Forums\Search\ForumDatabaseSearch
  ForumSearch: SilverStripe\Forums\Search\ForumSearch
  ForumSearchProvider: SilverStripe\Forums\Search\ForumSearchProvider
  ForumSphinxSearch: SilverStripe\Forums\Search\ForumSphinxSearch
  ForumRole: SilverStripe\Forum\Extensions\ForumRole
  ForumRole_Validator: SilverStripe\Forum\Extensions\ForumRole_Validator
  ForumSpamPostExtension: SilverStripe\Forum\Extensions\ForumSpamPostExtension
  ForumMemberProfile: SilverStripe\Forum\Controllers\ForumMemberProfile
  CheckableOption: SilverStripe\Forum\Controllers\CheckableOption
  ForumCountryDropdownField: SilverStripe\Forum\Controllers\ForumCountryDropdownField
  ForumCategory: SilverStripe\Forum\Models\ForumCategory
  ForumThread: SilverStripe\Forum\Models\ForumThread
  ForumThread_Subscription: SilverStripe\Forum\Models\ForumThread_Subscription
  Post: SilverStripe\Forum\Models\Post
  Post_Attachment: SilverStripe\Forum\Models\Post_Attachment
  Forum: SilverStripe\Forum\Pages\Forum
  Forum_Controller: SilverStripe\Forum\Pages\Forum_Controller
  Forum_DataQuery: SilverStripe\Forum\Pages\Forum_DataQuery
  ForumHolder: SilverStripe\Forum\Pages\ForumHolder
  ForumHolder_Controller: SilverStripe\Forum\Pages\ForumHolder_Controller
  ForumReport_MemberSignups: SilverStripe\Forum\Reports\ForumReport_MemberSignups
  ForumReport_MonthlyPosts: SilverStripe\Forum\Reports\ForumReport_MonthlyPosts
  ForumHolderTest: SilverStripe\Forum\Tests\ForumHolderTest
  ForumMemberProfileTest: SilverStripe\Forum\Tests\ForumMemberProfileTest
  ForumReportTest: SilverStripe\Forum\Tests\ForumReportTest
  ForumTest: SilverStripe\Forum\Tests\ForumTest
  ForumThreadTest: SilverStripe\Forum\Tests\ForumThreadTest
  PostTest: SilverStripe\Forum\Tests\PostTest
