mappings:
  ForumDatabaseSearch: SilverStripe\Forum\Search\ForumDatabaseSearch
  ForumSearch: SilverStripe\Forum\Search\ForumSearch
  ForumSearchProvider: SilverStripe\Forum\Search\ForumSearchProvider
  ForumSphinxSearch: SilverStripe\Forum\Search\ForumSphinxSearch
  ForumRole: SilverStripe\Forum\Extension\ForumRole
  ForumRole_Validator: SilverStripe\Forum\Extension\ForumRoleValidator
  ForumSpamPostExtension: SilverStripe\Forum\Extension\ForumSpamPostExtension
  ForumMemberProfile: SilverStripe\Forum\Controller\ForumMemberProfile
  CheckableOption: SilverStripe\Forum\Controller\CheckableOption
  ForumCountryDropdownField: SilverStripe\Forum\Controller\ForumCountryDropdownField
  ForumCategory: SilverStripe\Forum\Model\ForumCategory
  ForumThread: SilverStripe\Forum\Model\ForumThread
  ForumThread_Subscription: SilverStripe\Forum\Model\ForumThreadSubscription
  Post: SilverStripe\Forum\Model\Post
  Post_Attachment: SilverStripe\Forum\Model\PostAttachment
  Forum: SilverStripe\Forum\Page\ForumPage
  Forum_Controller: SilverStripe\Forum\Page\ForumPageController
  Forum_DataQuery: SilverStripe\Forum\Page\ForumDataQuery
  ForumHolder: SilverStripe\Forum\Page\ForumHolderPage
  ForumHolder_Controller: SilverStripe\Forum\Page\ForumHolderPageController
  ForumReport_MemberSignups: SilverStripe\Forum\Report\ForumReportMemberSignups
  ForumReport_MonthlyPosts: SilverStripe\Forum\Report\ForumReportMonthlyPosts
  ForumHolderTest: SilverStripe\Forum\Tests\ForumHolderTest
  ForumMemberProfileTest: SilverStripe\Forum\Tests\ForumMemberProfileTest
  ForumReportTest: SilverStripe\Forum\Tests\ForumReportTest
  ForumTest: SilverStripe\Forum\Tests\ForumTest
  ForumThreadTest: SilverStripe\Forum\Tests\ForumThreadTest
  PostTest: SilverStripe\Forum\Tests\PostTest
